[options]
work_mode = "sys"
library = "GdkMacos"
version = "4.0"
min_cfg_version = "4.0.0"
single_version_file = "."
girs_directories = ["../../gir-files"]

external_libraries = [
    "GLib",
]

[external_libraries]
gdk4 = "Gdk"


[[object]]
name = "GdkMacos.MacosMonitor"
status = "generate"
    [[object.function]]
    name = "get_geometry"
    ignore = true # The function does not exists