// This file was generated by gir (https://github.com/gtk-rs/gir)
// from gir-files (https://github.com/gtk-rs/gir-files)
// DO NOT EDIT

use glib::object::Cast;
use glib::object::IsA;
use glib::signal::connect_raw;
use glib::signal::SignalHandlerId;
use glib::translate::*;
use glib::StaticType;
use glib::ToValue;
use glib_sys;
use gtk_sys;
use std::boxed::Box as Box_;
use std::fmt;
use std::mem::transmute;
use LayoutChild;
use LayoutManager;
use Widget;

glib_wrapper! {
    pub struct GridLayoutChild(Object<gtk_sys::GtkGridLayoutChild, gtk_sys::GtkGridLayoutChildClass, GridLayoutChildClass>) @extends LayoutChild;

    match fn {
        get_type => || gtk_sys::gtk_grid_layout_child_get_type(),
    }
}

#[derive(Clone, Default)]
pub struct GridLayoutChildBuilder {
    column: Option<i32>,
    column_span: Option<i32>,
    row: Option<i32>,
    row_span: Option<i32>,
    child_widget: Option<Widget>,
    layout_manager: Option<LayoutManager>,
}

impl GridLayoutChildBuilder {
    pub fn new() -> Self {
        Self::default()
    }

    pub fn build(self) -> GridLayoutChild {
        let mut properties: Vec<(&str, &dyn ToValue)> = vec![];
        if let Some(ref column) = self.column {
            properties.push(("column", column));
        }
        if let Some(ref column_span) = self.column_span {
            properties.push(("column-span", column_span));
        }
        if let Some(ref row) = self.row {
            properties.push(("row", row));
        }
        if let Some(ref row_span) = self.row_span {
            properties.push(("row-span", row_span));
        }
        if let Some(ref child_widget) = self.child_widget {
            properties.push(("child-widget", child_widget));
        }
        if let Some(ref layout_manager) = self.layout_manager {
            properties.push(("layout-manager", layout_manager));
        }
        let ret = glib::Object::new(GridLayoutChild::static_type(), &properties)
            .expect("object new")
            .downcast::<GridLayoutChild>()
            .expect("downcast");
        ret
    }

    pub fn column(mut self, column: i32) -> Self {
        self.column = Some(column);
        self
    }

    pub fn column_span(mut self, column_span: i32) -> Self {
        self.column_span = Some(column_span);
        self
    }

    pub fn row(mut self, row: i32) -> Self {
        self.row = Some(row);
        self
    }

    pub fn row_span(mut self, row_span: i32) -> Self {
        self.row_span = Some(row_span);
        self
    }

    pub fn child_widget<P: IsA<Widget>>(mut self, child_widget: &P) -> Self {
        self.child_widget = Some(child_widget.clone().upcast());
        self
    }

    pub fn layout_manager<P: IsA<LayoutManager>>(mut self, layout_manager: &P) -> Self {
        self.layout_manager = Some(layout_manager.clone().upcast());
        self
    }
}

pub const NONE_GRID_LAYOUT_CHILD: Option<&GridLayoutChild> = None;

pub trait GridLayoutChildExt: 'static {
    fn get_column(&self) -> i32;

    fn get_column_span(&self) -> i32;

    fn get_row(&self) -> i32;

    fn get_row_span(&self) -> i32;

    fn set_column(&self, column: i32);

    fn set_column_span(&self, span: i32);

    fn set_row(&self, row: i32);

    fn set_row_span(&self, span: i32);

    fn connect_property_column_notify<F: Fn(&Self) + 'static>(&self, f: F) -> SignalHandlerId;

    fn connect_property_column_span_notify<F: Fn(&Self) + 'static>(&self, f: F) -> SignalHandlerId;

    fn connect_property_row_notify<F: Fn(&Self) + 'static>(&self, f: F) -> SignalHandlerId;

    fn connect_property_row_span_notify<F: Fn(&Self) + 'static>(&self, f: F) -> SignalHandlerId;
}

impl<O: IsA<GridLayoutChild>> GridLayoutChildExt for O {
    fn get_column(&self) -> i32 {
        unsafe { gtk_sys::gtk_grid_layout_child_get_column(self.as_ref().to_glib_none().0) }
    }

    fn get_column_span(&self) -> i32 {
        unsafe { gtk_sys::gtk_grid_layout_child_get_column_span(self.as_ref().to_glib_none().0) }
    }

    fn get_row(&self) -> i32 {
        unsafe { gtk_sys::gtk_grid_layout_child_get_row(self.as_ref().to_glib_none().0) }
    }

    fn get_row_span(&self) -> i32 {
        unsafe { gtk_sys::gtk_grid_layout_child_get_row_span(self.as_ref().to_glib_none().0) }
    }

    fn set_column(&self, column: i32) {
        unsafe {
            gtk_sys::gtk_grid_layout_child_set_column(self.as_ref().to_glib_none().0, column);
        }
    }

    fn set_column_span(&self, span: i32) {
        unsafe {
            gtk_sys::gtk_grid_layout_child_set_column_span(self.as_ref().to_glib_none().0, span);
        }
    }

    fn set_row(&self, row: i32) {
        unsafe {
            gtk_sys::gtk_grid_layout_child_set_row(self.as_ref().to_glib_none().0, row);
        }
    }

    fn set_row_span(&self, span: i32) {
        unsafe {
            gtk_sys::gtk_grid_layout_child_set_row_span(self.as_ref().to_glib_none().0, span);
        }
    }

    fn connect_property_column_notify<F: Fn(&Self) + 'static>(&self, f: F) -> SignalHandlerId {
        unsafe extern "C" fn notify_column_trampoline<P, F: Fn(&P) + 'static>(
            this: *mut gtk_sys::GtkGridLayoutChild,
            _param_spec: glib_sys::gpointer,
            f: glib_sys::gpointer,
        ) where
            P: IsA<GridLayoutChild>,
        {
            let f: &F = &*(f as *const F);
            f(&GridLayoutChild::from_glib_borrow(this).unsafe_cast_ref())
        }
        unsafe {
            let f: Box_<F> = Box_::new(f);
            connect_raw(
                self.as_ptr() as *mut _,
                b"notify::column\0".as_ptr() as *const _,
                Some(transmute::<_, unsafe extern "C" fn()>(
                    notify_column_trampoline::<Self, F> as *const (),
                )),
                Box_::into_raw(f),
            )
        }
    }

    fn connect_property_column_span_notify<F: Fn(&Self) + 'static>(&self, f: F) -> SignalHandlerId {
        unsafe extern "C" fn notify_column_span_trampoline<P, F: Fn(&P) + 'static>(
            this: *mut gtk_sys::GtkGridLayoutChild,
            _param_spec: glib_sys::gpointer,
            f: glib_sys::gpointer,
        ) where
            P: IsA<GridLayoutChild>,
        {
            let f: &F = &*(f as *const F);
            f(&GridLayoutChild::from_glib_borrow(this).unsafe_cast_ref())
        }
        unsafe {
            let f: Box_<F> = Box_::new(f);
            connect_raw(
                self.as_ptr() as *mut _,
                b"notify::column-span\0".as_ptr() as *const _,
                Some(transmute::<_, unsafe extern "C" fn()>(
                    notify_column_span_trampoline::<Self, F> as *const (),
                )),
                Box_::into_raw(f),
            )
        }
    }

    fn connect_property_row_notify<F: Fn(&Self) + 'static>(&self, f: F) -> SignalHandlerId {
        unsafe extern "C" fn notify_row_trampoline<P, F: Fn(&P) + 'static>(
            this: *mut gtk_sys::GtkGridLayoutChild,
            _param_spec: glib_sys::gpointer,
            f: glib_sys::gpointer,
        ) where
            P: IsA<GridLayoutChild>,
        {
            let f: &F = &*(f as *const F);
            f(&GridLayoutChild::from_glib_borrow(this).unsafe_cast_ref())
        }
        unsafe {
            let f: Box_<F> = Box_::new(f);
            connect_raw(
                self.as_ptr() as *mut _,
                b"notify::row\0".as_ptr() as *const _,
                Some(transmute::<_, unsafe extern "C" fn()>(
                    notify_row_trampoline::<Self, F> as *const (),
                )),
                Box_::into_raw(f),
            )
        }
    }

    fn connect_property_row_span_notify<F: Fn(&Self) + 'static>(&self, f: F) -> SignalHandlerId {
        unsafe extern "C" fn notify_row_span_trampoline<P, F: Fn(&P) + 'static>(
            this: *mut gtk_sys::GtkGridLayoutChild,
            _param_spec: glib_sys::gpointer,
            f: glib_sys::gpointer,
        ) where
            P: IsA<GridLayoutChild>,
        {
            let f: &F = &*(f as *const F);
            f(&GridLayoutChild::from_glib_borrow(this).unsafe_cast_ref())
        }
        unsafe {
            let f: Box_<F> = Box_::new(f);
            connect_raw(
                self.as_ptr() as *mut _,
                b"notify::row-span\0".as_ptr() as *const _,
                Some(transmute::<_, unsafe extern "C" fn()>(
                    notify_row_span_trampoline::<Self, F> as *const (),
                )),
                Box_::into_raw(f),
            )
        }
    }
}

impl fmt::Display for GridLayoutChild {
    fn fmt(&self, f: &mut fmt::Formatter) -> fmt::Result {
        write!(f, "GridLayoutChild")
    }
}
