[options]
work_mode = "sys"
library = "GdkWayland"
version = "4.0"
min_cfg_version = "4.0.0"
single_version_file = "."
dox_feature_dependencies = ["xkbcommon-sys"]
girs_directories = ["../../gir-files"]

external_libraries = [
    "GLib",
]

[[feature_dependencies]]
version = "4.4"
dependencies = [
    "xkbcommon-sys"
]
