// This file was generated by gir (https://github.com/gtk-rs/gir)
// from gir-files (https://github.com/gtk-rs/gir-files)
// DO NOT EDIT

use glib::object::Cast;
use glib::object::IsA;
use glib::signal::SignalHandlerId;
use glib::signal::connect_raw;
use glib::translate::*;
use glib_sys;
use gtk_sys;
use std::boxed::Box as Box_;
use std::fmt;
use std::mem::transmute;

glib_wrapper! {
    pub struct AccelGroup(Object<gtk_sys::GtkAccelGroup, gtk_sys::GtkAccelGroupClass, AccelGroupClass>);

    match fn {
        get_type => || gtk_sys::gtk_accel_group_get_type(),
    }
}

impl AccelGroup {
    pub fn new() -> AccelGroup {
        assert_initialized_main_thread!();
        unsafe {
            from_glib_full(gtk_sys::gtk_accel_group_new())
        }
    }

    //pub fn from_accel_closure(closure: /*Ignored*/&glib::Closure) -> Option<AccelGroup> {
    //    unsafe { TODO: call gtk_sys:gtk_accel_group_from_accel_closure() }
    //}
}

impl Default for AccelGroup {
    fn default() -> Self {
        Self::new()
    }
}

pub const NONE_ACCEL_GROUP: Option<&AccelGroup> = None;

pub trait AccelGroupExt: 'static {
    //fn activate(&self, accel_quark: /*Ignored*/glib::Quark, acceleratable: /*Ignored*/&glib::Object, accel_key: u32, accel_mods: /*Ignored*/gdk::ModifierType) -> bool;

    //fn connect(&self, accel_key: u32, accel_mods: /*Ignored*/gdk::ModifierType, accel_flags: AccelFlags, closure: /*Ignored*/&glib::Closure);

    //fn connect_by_path(&self, accel_path: &str, closure: /*Ignored*/&glib::Closure);

    //fn disconnect(&self, closure: /*Ignored*/Option<&glib::Closure>) -> bool;

    //fn disconnect_key(&self, accel_key: u32, accel_mods: /*Ignored*/gdk::ModifierType) -> bool;

    //fn find(&self, find_func: /*Unimplemented*/FnMut(/*Ignored*/AccelKey, /*Ignored*/glib::Closure) -> bool, data: /*Unimplemented*/Option<Fundamental: Pointer>) -> /*Ignored*/Option<AccelKey>;

    fn get_is_locked(&self) -> bool;

    //fn get_modifier_mask(&self) -> /*Ignored*/gdk::ModifierType;

    fn lock(&self);

    //fn query(&self, accel_key: u32, accel_mods: /*Ignored*/gdk::ModifierType) -> /*Ignored*/Vec<AccelGroupEntry>;

    fn unlock(&self);

    //fn connect_accel_activate<Unsupported or ignored types>(&self, f: F) -> SignalHandlerId;

    //fn connect_accel_changed<Unsupported or ignored types>(&self, f: F) -> SignalHandlerId;

    fn connect_property_is_locked_notify<F: Fn(&Self) + 'static>(&self, f: F) -> SignalHandlerId;

    fn connect_property_modifier_mask_notify<F: Fn(&Self) + 'static>(&self, f: F) -> SignalHandlerId;
}

impl<O: IsA<AccelGroup>> AccelGroupExt for O {
    //fn activate(&self, accel_quark: /*Ignored*/glib::Quark, acceleratable: /*Ignored*/&glib::Object, accel_key: u32, accel_mods: /*Ignored*/gdk::ModifierType) -> bool {
    //    unsafe { TODO: call gtk_sys:gtk_accel_group_activate() }
    //}

    //fn connect(&self, accel_key: u32, accel_mods: /*Ignored*/gdk::ModifierType, accel_flags: AccelFlags, closure: /*Ignored*/&glib::Closure) {
    //    unsafe { TODO: call gtk_sys:gtk_accel_group_connect() }
    //}

    //fn connect_by_path(&self, accel_path: &str, closure: /*Ignored*/&glib::Closure) {
    //    unsafe { TODO: call gtk_sys:gtk_accel_group_connect_by_path() }
    //}

    //fn disconnect(&self, closure: /*Ignored*/Option<&glib::Closure>) -> bool {
    //    unsafe { TODO: call gtk_sys:gtk_accel_group_disconnect() }
    //}

    //fn disconnect_key(&self, accel_key: u32, accel_mods: /*Ignored*/gdk::ModifierType) -> bool {
    //    unsafe { TODO: call gtk_sys:gtk_accel_group_disconnect_key() }
    //}

    //fn find(&self, find_func: /*Unimplemented*/FnMut(/*Ignored*/AccelKey, /*Ignored*/glib::Closure) -> bool, data: /*Unimplemented*/Option<Fundamental: Pointer>) -> /*Ignored*/Option<AccelKey> {
    //    unsafe { TODO: call gtk_sys:gtk_accel_group_find() }
    //}

    fn get_is_locked(&self) -> bool {
        unsafe {
            from_glib(gtk_sys::gtk_accel_group_get_is_locked(self.as_ref().to_glib_none().0))
        }
    }

    //fn get_modifier_mask(&self) -> /*Ignored*/gdk::ModifierType {
    //    unsafe { TODO: call gtk_sys:gtk_accel_group_get_modifier_mask() }
    //}

    fn lock(&self) {
        unsafe {
            gtk_sys::gtk_accel_group_lock(self.as_ref().to_glib_none().0);
        }
    }

    //fn query(&self, accel_key: u32, accel_mods: /*Ignored*/gdk::ModifierType) -> /*Ignored*/Vec<AccelGroupEntry> {
    //    unsafe { TODO: call gtk_sys:gtk_accel_group_query() }
    //}

    fn unlock(&self) {
        unsafe {
            gtk_sys::gtk_accel_group_unlock(self.as_ref().to_glib_none().0);
        }
    }

    //fn connect_accel_activate<Unsupported or ignored types>(&self, f: F) -> SignalHandlerId {
    //    Ignored acceleratable: GObject.Object
    //    Ignored modifier: Gdk.ModifierType
    //}

    //fn connect_accel_changed<Unsupported or ignored types>(&self, f: F) -> SignalHandlerId {
    //    Ignored modifier: Gdk.ModifierType
    //    Ignored accel_closure: GObject.Closure
    //}

    fn connect_property_is_locked_notify<F: Fn(&Self) + 'static>(&self, f: F) -> SignalHandlerId {
        unsafe {
            let f: Box_<F> = Box_::new(f);
            connect_raw(self.as_ptr() as *mut _, b"notify::is-locked\0".as_ptr() as *const _,
                Some(transmute(notify_is_locked_trampoline::<Self, F> as usize)), Box_::into_raw(f))
        }
    }

    fn connect_property_modifier_mask_notify<F: Fn(&Self) + 'static>(&self, f: F) -> SignalHandlerId {
        unsafe {
            let f: Box_<F> = Box_::new(f);
            connect_raw(self.as_ptr() as *mut _, b"notify::modifier-mask\0".as_ptr() as *const _,
                Some(transmute(notify_modifier_mask_trampoline::<Self, F> as usize)), Box_::into_raw(f))
        }
    }
}

unsafe extern "C" fn notify_is_locked_trampoline<P, F: Fn(&P) + 'static>(this: *mut gtk_sys::GtkAccelGroup, _param_spec: glib_sys::gpointer, f: glib_sys::gpointer)
where P: IsA<AccelGroup> {
    let f: &F = &*(f as *const F);
    f(&AccelGroup::from_glib_borrow(this).unsafe_cast())
}

unsafe extern "C" fn notify_modifier_mask_trampoline<P, F: Fn(&P) + 'static>(this: *mut gtk_sys::GtkAccelGroup, _param_spec: glib_sys::gpointer, f: glib_sys::gpointer)
where P: IsA<AccelGroup> {
    let f: &F = &*(f as *const F);
    f(&AccelGroup::from_glib_borrow(this).unsafe_cast())
}

impl fmt::Display for AccelGroup {
    fn fmt(&self, f: &mut fmt::Formatter) -> fmt::Result {
        write!(f, "AccelGroup")
    }
}
