// This file was generated by gir (https://github.com/gtk-rs/gir)
// from gir-files (https://github.com/gtk-rs/gir-files)
// DO NOT EDIT

use Accessible;
use WidgetAccessible;
use atk;
use glib::translate::*;
use gtk_sys;
use std::fmt;

glib_wrapper! {
    pub struct LabelAccessible(Object<gtk_sys::GtkLabelAccessible, gtk_sys::GtkLabelAccessibleClass, LabelAccessibleClass>) @extends WidgetAccessible, Accessible, atk::Object;

    match fn {
        get_type => || gtk_sys::gtk_label_accessible_get_type(),
    }
}

impl LabelAccessible {}

pub const NONE_LABEL_ACCESSIBLE: Option<&LabelAccessible> = None;

impl fmt::Display for LabelAccessible {
    fn fmt(&self, f: &mut fmt::Formatter) -> fmt::Result {
        write!(f, "LabelAccessible")
    }
}
