[options]
work_mode = "sys"
library = "Gsk"
version = "4.0"
min_cfg_version = "4.0.0"
single_version_file = "."
girs_directories = ["../../gir-files"]

external_libraries = [
    "GLib",
    "GObject",
    "Pango",
    "Cairo",
    "Graphene",
]

[external_libraries]
gdk4 = "Gdk"


[[object]]
name = "Gsk.BroadwayRenderer"
status = "generate"
cfg_condition = "feature = \"broadway\""
    [[object.function]]
    pattern = "(new|get_type)"
    cfg_condition = "feature = \"broadway\""

[[object]]
name = "Gsk.BroadwayRendererClass"
status = "generate"
cfg_condition = "feature = \"broadway\""

[[object]]
name = "Gsk.VulkanRenderer"
status = "generate"
cfg_condition = "feature = \"vulkan\""
    [[object.function]]
    pattern = "(new|get_type)"
    cfg_condition = "feature = \"vulkan\""

[[object]]
name = "Gsk.VulkanRendererClass"
status = "generate"
cfg_condition = "feature = \"vulkan\""
