[options]
work_mode = "sys"
library = "Gtk"
version = "4.0"
min_cfg_version = "4.0.0"
single_version_file = "."
girs_directories = ["../../gir-files"]

external_libraries = [
    "GLib",
    "GObject",
    "Gio",
    "GdkPixbuf",
    "Pango",
    "Cairo",
    "Graphene",
]

ignore = [
    "Gtk.BINARY_AGE",
    "Gtk.INTERFACE_AGE",
    "Gtk.MAJOR_VERSION",
    "Gtk.MICRO_VERSION",
    "Gtk.MINOR_VERSION",
]

[external_libraries]
gdk4 = "Gdk"
gsk4 = "Gsk"

[[object]]
name = "Gtk.ExpressionWatch"
status = "generate"
    [[object.function]]
    name = "get_type"
    version = "4.2"
